### ISSUE TITLE
Enhancement: Improve User Experience for Empty Search Results 

### ISSUE THREAD

**Issue by salma2vec** [IdealisticINTJ/Shop_Scout#1]
**Is your feature request related to a problem? Please describe.**
Currently, when a user performs a search that yields no results, the application does not handle this scenario gracefully. Users may be confused or frustrated when presented with an empty result set.

**Describe the solution you'd like**
Implement a more user-friendly experience when search results are empty. Instead of displaying a blank or confusing screen, provide a clear and concise message to the user, explaining that no results were found based on their search criteria. Additionally, consider offering suggestions or alternative actions, such as refining the search terms or exploring popular categories.

**Describe alternatives you've considered**
An alternative solution could be to display default content or recommendations when no search results are found. This could include showcasing popular products or categories to keep the user engaged even in the absence of specific search results.

**Additional context**
Consider incorporating visual elements such as icons or illustrations to make the message more engaging and informative. This enhancement aims to improve the overall user experience and reduce potential frustration when users encounter empty search results.

**Comment by raizestudio** [comment]
Hello, i'd like to work on this one, can you please assign it to me ?

**Comment by salma2vec** [comment]
There you go. Assigned!

**Comment by raizestudio** [comment]
You can check pr #4 ! 🙂
